### ISSUE TITLE
App does not load on android 4.4.2

### ISSUE THREAD

**Issue by hvhaaren** [oracle/cordova-plugin-emm-app-config#4]
I'm using your plugin in our app and it works very good, Thanks. 
I do have an issue with older android versions. Our app does not startup (blank screen) and shows the 'deviceready has not fired after 5 seconds.' error (see code below) after removing this plugin it works the app works again. Is this a known issue or can you help me resolving this? Our customors can not use our app anymore. I tested this on Samsung S4 mini and Samsung Tab SM-T310.

Kind regards, Hugo

 window.setTimeout(function() {
            if (channel.onDeviceReady.state != 2) {
                console.log('deviceready has not fired after 5 seconds.');
                logUnfiredChannels(platformInitChannelsArray);
                logUnfiredChannels(channel.deviceReadyChannelsArray);
            }
        }, 5000);

**Comment by lpchanora** [comment]
Hi @hvhaaren , does the exact same app work on latest version of Android but not 4.4.2?  Which version of cordova-plugin-emm-app-config are you using?

There was a known bug in v1.0.0 of the plugin that prevented it from firing the ready event if cordova-plugin-device is also added to the app.  This has been fixed in v1.0.1.

However, that wouldn't explain it if the exact same app works on later version of Android but not older version.

**Comment by hvhaaren** [comment]
Hi Leon Chan, Thanks for your response. I'm using version 1.0.2. The exact same app works if I comment all the lines below. It seems that those lines result in a an error so the pluginresult.status.ok is never returned. 

try
    {
     //Context context = cordova.getActivity().getApplicationContext();
     //RestrictionsManager resManager = RestrictionsManager)context.getSystemService(Context.RESTRICTIONS_SERVICE);
     //Bundle restrictions = resManager.getApplicationRestrictions();
    //JSONObject appConfig = _convertBundleToJSON(restrictions);
     //result = new PluginResult(PluginResult.Status.OK, appConfig);
     result = new PluginResult(PluginResult.Status.OK);
    }
    catch (JSONException e) ........

If I put back the two lines below it fails again. Are there additional permissions needed on android 4.4.2 to access the RESTRICTIONS_SERVICE? If you have something I could try let me know I can test it on an old device here. 

Context context = cordova.getActivity().getApplicationContext();
RestrictionsManager resManager = RestrictionsManager)context.getSystemService(Context.RESTRICTIONS_SERVICE);

**Comment by lpchanora** [comment]
Hi @hvhaaren,

According to Android Developer doc, RestrictionManager is added in API level 21:
https://developer.android.com/reference/android/content/RestrictionsManager.html

API level 21 corresponds to Android 5.0:
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels

This means only devices with Android 5.0 or later can use the plugin to access AppConfig data.

**Comment by MrTechGadget** [comment]
Lol, I saw your reply just now and realized I had this in my drafts!

I think you will find that is because these features were added in Android
5.0.
https://developer.android.com/about/versions/android-5.0.html

**Comment by hvhaaren** [comment]
Ok, this clarifies it. I already did a fix to not load the plugin for older versions. I will update our documentation that the feature is available from android 5.0 and higher. Thanks for your support.
