### ISSUE TITLE
Browser is crashing.

### ISSUE THREAD

**Issue by ck88ger** [oracle/cordova-plugin-emm-app-config#5]
Hi everyone,

is use this plugin successful. But if i start my application for Browser, its crashing.  i have a hybrid app for ios/android/web.

I get this error:
- Error: exec proxy not found for :: EmmAPpConfig :: getConfigInfo
- [ERROR] Error from EmmAppConfig.getConfigInfo: Missing Command Error

I know that is only supported for smartphones. But i use the web app for other stuff. This plugin is for me to handle smartphone stuff. Have anybody an idea? 

thanks..

**Comment by MrTechGadget** [comment]
Yes, have this code load only if the platform is iOS or Android and
Cordova.

**Comment by ck88ger** [comment]
You are right.

I used this plugin to resolve it:
https://cordova.apache.org/docs/en/latest/plugin_ref/plugman.html

thanks!

**Comment by lpchanora** [comment]
Application should check the platform before calling the plugin.  This give the app a chance to handle it differently if the app config is not available.

**Comment by gaspachoandalus** [comment]
@lj222kj [fork](https://github.com/lj222kj/cordova-plugin-emm-app-config) works fine on the browser platform
